ecommerce/src/Entity/Product.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="product")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="product", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Platform", mappedBy="product")
     */
    private $platforms;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Panier", mappedBy="product")
     */
    private $paniers;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Historical", mappedBy="products")
     */
    private $historicals;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Favorite", mappedBy="product")
     */
    private $favorites;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->platform = new ArrayCollection();
        $this->platforms = new ArrayCollection();
        $this->paniers = new ArrayCollection();
        $this->historicals = new ArrayCollection();
        $this->favorites = new ArrayCollection();
    }


    /**
     * Permet d'initialiser le slug (ne pas oublier de dire a la class ... ligne 15 callbacks)
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeSlug()
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à un produit
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author) {
        foreach ($this->comments as $comment) {
            if($comment->getAuthor() === $author) return $comment;
        }
        return null;
    }


    /**
     * Permt d'obtenir la moyenne globale des notes pour cette annonce
     *
     * @param ArrayCollection $comments
     */
    public function getAvgRatings()
    {
        $sum = array_reduce($this->comments->toArray(), function($total, $comment) {
            return $total + $comment->getRating();
        }, 0);

        if(count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setProduct($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getProduct() === $this) {
                $comment->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Platform[]
     */
    public function getPlatforms(): Collection
    {
        return $this->platforms;
    }

    public function addPlatform(Platform $platform): self
    {
        if (!$this->platforms->contains($platform)) {
            $this->platforms[] = $platform;
            $platform->addProduct($this);
        }

        return $this;
    }

    public function removePlatform(Platform $platform): self
    {
        if ($this->platforms->contains($platform)) {
            $this->platforms->removeElement($platform);
            $platform->removeProduct($this);
        }

        return $this;
    }

    /**
     * @return Collection|Panier[]
     */
    public function getPaniers(): Collection
    {
        return $this->paniers;
    }

    public function addPanier(Panier $panier): self
    {
        if (!$this->paniers->contains($panier)) {
            $this->paniers[] = $panier;
            $panier->addProduct($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): self
    {
        if ($this->paniers->contains($panier)) {
            $this->paniers->removeElement($panier);
            $panier->removeProduct($this);
        }

        return $this;
    }

    /**
     * @return Collection|Historical[]
     */
    public function getHistoricals(): Collection
    {
        return $this->historicals;
    }

    public function addHistorical(Historical $historical): self
    {
        if (!$this->historicals->contains($historical)) {
            $this->historicals[] = $historical;
            $historical->addProduct($this);
        }

        return $this;
    }

    public function removeHistorical(Historical $historical): self
    {
        if ($this->historicals->contains($historical)) {
            $this->historicals->removeElement($historical);
            $historical->removeProduct($this);
        }

        return $this;
    }

    /**
     * @return Collection|Favorite[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
            $favorite->addProduct($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorites->contains($favorite)) {
            $this->favorites->removeElement($favorite);
            $favorite->removeProduct($this);
        }

        return $this;
    }

    public function __toString()
    {
        return(string) ($this->title);
    }
}

ecommerce/src/Controller/PlatformController.php
<?php

namespace App\Controller;

use App\Entity\Platform;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PlatformController extends AbstractController
{
    /**
     * @Route("/plateforme/{id}", name="platform_index")
     * @param Platform $category
     * @return Response
     */
    public function index(Platform $platform)
    {
        return $this->render('platform/index.html.twig', [
            'platform' => $platform,
        ]);
    }
}

ecommerce/templates/platform/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plateforme : {{ platform.name }}{% endblock %}

{% block body %}
    <div class="container">
        {% if platform.product is empty %}
            <div class="text-center h1 mt-5">Il n'y a aucun produit en vente sur cette plateforme pour le moment</div>
        {% else %}
        <h1 class="text-center mt-4">{{ platform.name }}</h1>
        <p class="text-center alert alert-info mt-4">Il y'a actuellement <u>{{ platform.product | length }} jeux</u> en vente pour cette plateforme</p>
        <div class="row">
            {% for product in platform.product %}
                <div class="card card-product-list p-3 mb-4">
                    <div class="row no-gutters">
                        <aside class="col-md-3">
                            <img class="w-100" src="{{product.coverImage}}">
                        </aside> <!-- col.// -->
                        <div class="col-md-6 px-4">
                            <div class="info-main border-right mr-4">
                                <h3 class="title text-capitalize">{{ product.title }}</h3>
                                <div class="row">
                                    <div class="col-md-6 pt-3 blockquote text-muted display-4">
                                        <p class="blockquote-footer">Catégorie : <a href="{{ path('category_index', {'id': product.category.id}) }}">{{ product.category.name }}</a></p>
                                        <p class="blockquote-footer">Plateforme{% if product.platforms | length > 1 %}s{% endif %} :
                                            {% for platform in product.platforms %}
                                                <a href="{{ path('platform_index', {'id': platform.id}) }}">
                                                    {{ platform.name }}
                                                </a>
                                                {% if not loop.last %}/{% endif %}
                                            {% endfor %}
                                        </p>
                                    </div>
                                    <div class="rating-wrap my-4 col-md-6">
                                        {% if product.comments | length > 0 %}
                                            {% include 'partials/rating.html.twig' with {'rating': product.avgRatings} %}
                                        {% else %}
                                            <p>Pas encore noté</p>
                                        {% endif %}
                                    </div> <!-- rating-wrap.// -->
                                </div>

                                <p class="text-justify pr-5">{{ product.description }}</p>
                            </div> <!-- info-main.// -->
                        </div> <!-- col.// -->
                        <aside class="col-sm-3">
                            <div class="info-aside">
                                <div class="price-wrap">
                                    <span class="price h4">{{ product.price }}&euro;</span>
                                </div> <!-- info-price-detail // -->
                                <br>
                                <p>
                                    <a href="{{ path('product_show', {'slug': product.slug}) }}" class="btn btn-info btn-block mb-1">Consulter</a>
                                    {% if app.user %}
                                    {% if product not in app.user.panier.product %}
                                    <a href="{{ path('product_add', {'slug': product.slug}) }}" class="btn btn-block btn-success">Ajouter au panier</a>
                                    {% else %}
                                <div class="inCart text-muted font-italic">
                                    Ce jeu est actuellement dans votre panier
                                </div>
                                {% endif %}
                                {% if product not in app.user.favorite.product %}
                                    <a href="{{ path('product_add_favorite', {'id': product.id}) }}" class="btn btn-outline-dark btn-block"><i class="fa fa-heart"></i>
                                        <span class="text">Ajouter aux favoris</span>
                                    </a>
                                {% else %}
                                    <a href="{{ path('favorite_delete', {'id': product.id}) }}" class="btn btn-outline-danger btn-block"><i class="fa fa-heart"></i>
                                        <span class="text">Retirer des favoris</span>
                                    </a>
                                {% endif %}
                                {% endif %}
                            </div> <!-- info-aside.// -->
                        </aside> <!-- col.// -->
                    </div> <!-- row.// -->
                </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>

{% endblock %}